In [2]:
import numpy as np

In [3]:
array_arange=np.arange(16)

In [4]:
array_arange

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [5]:
array_randint=np.random.randint(0,100,10)

In [8]:
array_randint

array([45, 89, 93, 28, 68, 38,  3, 97, 61, 50])

In [10]:
array_randint.shape

(10,)

In [11]:
array_randint=np.random.randint(0,50,550)

In [12]:
array_randint

array([43, 36,  3, 46, 42,  7, 25,  2,  3,  9, 38, 15, 47,  9, 27,  8, 39,
       23, 43,  5, 43, 49, 15, 20, 39, 49, 48,  4, 43,  5, 16, 16, 25, 14,
       38, 34, 42, 22, 14, 12,  2, 42, 27, 14, 17,  2, 13,  9, 37, 33, 35,
       16, 10, 16, 21, 40,  0, 40, 10, 43, 30, 16, 16, 15, 19, 19,  2,  8,
       22, 46, 12, 15, 20, 23, 33, 37,  0,  1, 18, 46, 14, 10,  9, 14,  3,
       15, 27, 25, 31, 43, 37, 19, 24, 24, 33, 33, 31, 35, 20, 14, 45, 16,
       44, 39, 41, 38,  2, 28, 26, 47,  5, 24, 20, 49, 49,  7, 15, 28, 38,
       25, 46, 10,  1, 38, 18, 45,  9, 14, 14, 15, 37, 22, 25,  1,  7, 49,
       22,  2, 39, 48, 12,  0, 30, 43,  3, 33,  4, 17, 15,  9, 10,  4, 10,
        1, 48, 46, 47, 16,  4, 30, 47, 31,  9, 23, 36, 38,  9, 37, 14, 10,
       21, 45, 13, 46, 37, 12, 16, 36, 13, 36, 48, 20, 18, 12,  6, 19, 34,
        3, 47, 33, 39, 46,  0, 38,  8, 19, 41, 49,  2, 23, 27,  5, 31, 14,
       30, 10, 47, 38, 31, 29, 15, 22, 48, 19, 40, 10,  3, 23,  0, 19, 44,
        1, 43,  7, 40, 30

In [13]:
array_randint.shape

(550,)

In [17]:
array_randint.max()

49

In [18]:
array_randint.min()

0

In [19]:
array_randint.argmax()

21

In [20]:
array_randint.argmin()

56

In [23]:
array_arange

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [25]:
array_arange.shape

(16,)

In [27]:
array_arange.dtype

dtype('int32')

In [30]:
array_1d=np.array([-10,-2,0,2,17,106,200])


In [31]:
array_1d

array([-10,  -2,   0,   2,  17, 106, 200])

In [32]:
array_1d[2]

0

In [33]:
array_1d[0]

-10

In [34]:
array_1d[0:2]

array([-10,  -2])

In [35]:
array_1d[0:1]

array([-10])

In [36]:
array_1d[1:4]

array([-2,  0,  2])

In [37]:
array_1d[2:5]

array([ 0,  2, 17])

In [38]:
array_1d[2]=234      

In [39]:
array_1d

array([-10,  -2, 234,   2,  17, 106, 200])

In [41]:
array_1d[5]=45


In [42]:
array_1d

array([-10,  -2, 234,   2,  17,  45, 200])

In [43]:
array_1d[4]

17

In [44]:
array_1d[4]=67

In [45]:
array_1d

array([-10,  -2, 234,   2,  67,  45, 200])

In [47]:
array_2d=np.arange(24)
array_2d.shape=(6,4)
array_2d

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [48]:
array_2d[2]

array([ 8,  9, 10, 11])

In [50]:
array_2d[4]

array([16, 17, 18, 19])

In [51]:
array_2d[-4]

array([ 8,  9, 10, 11])

In [52]:
array_2d[5,2]

22

In [53]:
array_2d[5][2]

22

In [54]:
row=5
col=2
array_2d[row,col]

22

In [60]:
array_2d=np.ones((3,4))
array_2d

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [61]:
array_2d[0]=33

In [62]:
array_2d

array([[33., 33., 33., 33.],
       [ 1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.]])

In [63]:
array_2d[1]=22

In [64]:
array_2d

array([[33., 33., 33., 33.],
       [22., 22., 22., 22.],
       [ 1.,  1.,  1.,  1.]])

In [65]:
array_2d[2]=44
array_2d

array([[33., 33., 33., 33.],
       [22., 22., 22., 22.],
       [44., 44., 44., 44.]])

In [66]:
array_2d+300

array([[333., 333., 333., 333.],
       [322., 322., 322., 322.],
       [344., 344., 344., 344.]])

In [67]:
array_2d*3

array([[ 99.,  99.,  99.,  99.],
       [ 66.,  66.,  66.,  66.],
       [132., 132., 132., 132.]])

In [69]:
array_2d[[0,1]]

array([[33., 33., 33., 33.],
       [22., 22., 22., 22.]])

In [71]:
array_2d[:,[2]]

array([[33.],
       [22.],
       [44.]])

In [77]:
array_2d=np.arange(36)
array_2d.shape=(6,6)
array_2d

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35]])

In [78]:
array_2d > 5

array([[False, False, False, False, False, False],
       [ True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True]])

In [79]:
array_2d <=6

array([[ True,  True,  True,  True,  True,  True],
       [ True, False, False, False, False, False],
       [False, False, False, False, False, False],
       [False, False, False, False, False, False],
       [False, False, False, False, False, False],
       [False, False, False, False, False, False]])

In [80]:
list_1=[1,2,3,4,5]                       #quiz 1
numpy_array=np.array(list_1)

In [81]:
numpy_array                           

array([1, 2, 3, 4, 5])

In [82]:
np.arange(6)                           #quiz 2

array([0, 1, 2, 3, 4, 5])

In [83]:
np.zeros(5)                             #quiz 3

array([0., 0., 0., 0., 0.])

In [89]:
np.zeros((3,4))                       #quiz 4

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [90]:
np.ones(5)                             #quiz 5

array([1., 1., 1., 1., 1.])

In [94]:
np.ones(5) + 9                          #quiz 6

array([10., 10., 10., 10., 10.])

In [96]:
np.arange(52,100,2)                       #quiz 7

array([52, 54, 56, 58, 60, 62, 64, 66, 68, 70, 72, 74, 76, 78, 80, 82, 84,
       86, 88, 90, 92, 94, 96, 98])

In [104]:
np.random.rand(11)

array([0.02907982, 0.18800577, 0.12875916, 0.45327024, 0.49554706,
       0.52188738, 0.91514965, 0.02703442, 0.79402979, 0.75725139,
       0.57424291])

In [105]:
np.arange(25)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [109]:
array_randint.shape

(550,)

In [110]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [1]:
import numpy as np


In [6]:
array_arange=np.arange(25)

In [11]:
array_arange

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22])

In [9]:
array_2d=np.arange(24)
array_2d.shape=(6,4)
array_2d

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [14]:
np.linspace(0,24,25)
array_2d=np.arange(25)
array_2d.shape=(5*5)
                

In [16]:
array_2d.shape

(25,)